name: 'Flask app action'
description: 'Setup Python, install Flask dependencies, and run a command'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  run-command:
    description: 'Command to run after setup (e.g. pytest, python app/main.py)'
    required: false
    default: 'pytest'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run command
      run: ${{ inputs.run-command }}
      shell: bash
